version: '3.8'

services:
  mysql-server:
   image: mysql:8
   container_name: mysql-server
   environment:
    MYSQL_ROOT_PASSWORD: 12345
    MYSQL_DATABASE: db 
    MYSQL_USER: mchamorro
    MYSQL_PASSWORD: 12345
   restart: unless-stopped
   ports:
     - 3310:3306
   networks:
     - net-app
   volumes:
     - vol-app:/var/lib/mysql
   healthcheck:
     test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost'] # comando de consulta al healtcheak.
     interval: 10s # Verificaciones cada x tiempo.
     timeout: 10s # Máximo de espero por intento.
     retries: 3 # Si falla 3 veces, se considera inactivo.
     start_interval: 5s # Espera de 5s antes de la primera verificación de ping.

networks:
  net-app:
    driver: bridge
    name: net-app

volumes:
  vol-app:
    name: vol-app
  vol-app-mongo:
    name: vol-app-mongo
   