version: '3.8'

services:
  # Servicio de la aplicaci贸n (Node.js)
  arq-hex-app:
    image: 748968218843.dkr.ecr.us-east-1.amazonaws.com/arq-hex-node # Usa la imagen de ECR
    container_name: app-nest
    restart: unless-stopped
    ports:
      - 3000:3000 # Exponemos el puerto 80 dentro del contenedor (puerto de la aplicaci贸n backend)

  # Servicio de Nginx (proxy inverso)
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80 # Exponemos el puerto 80 de Nginx hacia el exterior
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Montamos el archivo de configuraci贸n de Nginx
    depends_on:
      - arq-hex-app # Nginx depende del servicio de la aplicaci贸n para iniciar
    networks:
      - app-network # Definimos una red para que ambos servicios puedan comunicarse

networks:
  app-network:
    driver: bridge
